var DoStuff = false;
var socket; // define a global variable called socket 
var game;
var Gameobject = {};
var user;
var pass;
var order;
var access_token;
var GameId;
var cards;
var players;
var middlecard;
var middlecardchanged=false;
var playerWhoPlayed;
var IsnewCards = false;
var newCards;
var CanPlay =false;
var CanDraw = false;
var PlayerDrawedACardAnimation = false;
var PlayerDrawedACardAnimationData;